# Server example

# Webserver
services:
  usbadc10-ep-website:
    build:
      context: ../../ # Repository directory
      dockerfile: ./sites/usbadc10/Dockerfile
    container_name: usbadc10-ep-website
    ports:
      - "8080:8080"
    volumes:
      - epwebdrive:/app/sites/usbadc10/download

  epwebshare:
    build: ../../dockershare
    container_name: epwebshare
    ports:
      - "5000:22"
    volumes:
      - epwebdrive:/drive

volumes:
  epwebdrive: