# Server example

# Webserver
services:
  eyepoint-ep-website:
    build:
      context: ../../ # Repository directory
      dockerfile: ./sites/eyepoint/Dockerfile
    container_name: eyepoint-ep-website
    ports:
      - "8080:8080"
    volumes:
      - ./download:/app/sites/eyepoint/download