# Server example

# Webserver
services:
  eyepoint-ep-website:
    build:
      context: ../../ # Repository directory
      dockerfile: ./sites/eyepoint/Dockerfile
    container_name: eyepoint-ep-website
    ports:
      - "8080:8080"
    volumes:
      - epwebdrive:/app/sites/eyepoint/download

  epwebshare:
    build: ../../dockershare
    container_name: epwebshare
    ports:
      - "5000:22"
    volumes:
      - epwebdrive:/drive

volumes:
  epwebdrive: